spring.application.name=swim-club-backend

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=${SERVER_PORT:8089}

# Logging
logging.level.root=INFO
logging.level.com.swimclub=DEBUG

# JWT Configuration
jwt.secret=your_jwt_secret_key_make_it_long_and_secure_at_least_64_characters
jwt.expiration=86400000

app.backend.base-url=http://localhost:8082
app.verification.url=http://localhost:8082/api/auth/verify

# Jackson date configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# CORS Configuration
cors.allowed-origins=http://localhost:4200,http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*

# ===============================
# Spring AI / Ollama & MongoDB Configuration
# ===============================
spring.ai.ollama.base-url=http://ollama:11434
spring.ai.ollama.chat.model=qwen2.5:1.5b

spring.data.mongodb.uri=mongodb://mongodb:27017/ftn_natation

# ==========================================
# Configuration SMTP Google / Gmail Reel
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Dans le fichier application.properties du backend :
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://aquapro-keycloak:8080/realms/swimming-platform/protocol/openid-connect/certs